apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: alexakslabacr.azurecr.io/api:1.0.0
        env:
        - name: PORT
          value: "80"
        - name: SONG_SERVICE_BASE_URL
          value: "http://songs/songs"
        - name: CONTRACT_SERVICE_BASE_URL
          value: "http://contracts/contracts"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: api