version: "3.9"

services:
  songs:
    container_name: songs
    build: 
      context: ./songs
      dockerfile: ./Dockerfile
    ports:
      - "9100:80"
  contracts:
    container_name: contracts
    build: 
      context: ./contracts
      dockerfile: ./Dockerfile
    ports:
      - "9200:80"
  songapi:
    container_name: songapi
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
