version: "3.9"

services:
  songs:
    container_name: songs
    build: 
      context: .
      dockerfile: ./songs/Dockerfile
    ports:
      - "9100:80"
  contracts:
    container_name: contracts
    build: 
      context: .
      dockerfile: ./contracts/Dockerfile
    ports:
      - "9200:80"
  songapi:
    container_name: songapi
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "80:80"
