---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-app
  labels:
    app: songs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs
  template:
    metadata:
      labels:
        app: songs
    spec:
      containers:
      - name: songs
        image: pelasneakslabacr.azurecr.io/songs:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contracts-app
  labels:
    app: contracts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contracts
  template:
    metadata:
      labels:
        app: contracts
    spec:
      containers:
      - name: contracts
        image: pelasneakslabacr.azurecr.io/contracts:1.0.0
        ports:
        - containerPort: 80
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: pelasneakslabacr.azurecr.io/api:1.0.0
        ports:
        - containerPort: 80