apiVersion: v1
kind: Service
metadata:
  name: songs
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: songs
---
apiVersion: v1
kind: Service
metadata:
  name: contracts
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: contracts
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: api
